### ISSUE TITLE
Build Error - Set Working Directory Page

### ISSUE THREAD

**Issue by lwasser** [NEONInc/NEON-Data-Skills#55]
Hi @mjones01 
I'm working on this site and there is a build error in a page that you pushed. I think some of the includes may be incorrect. Please fix, build locally to test that things are working, then submit a PR for me to review.
Specific Error:
```
The page build failed with the following error:

A file was included in `_posts/R-stats/2016-01-08-Set-Working-Directory-In-R.md` that is a symlink or does not exist in your `_includes` directory. For more information, see https://help.github.com/articles/page-build-failed-file-is-a-symlink.
```
Build errors mean that new content added to the site will not render.
Don't worry about this - this week - focus on the teacher training.
Please complete this task by next Tuesday, 20 Jan or get in touch if you need more time.
Thank you!
Leah

**Comment by mjones01** [comment]
@lwasser 
1) The issue is about the _include files. This lesson uses the _data_Met-Time-Series.html file.   None of the Spatio-Temporal series data download _include files are in the Data Skills repo.  The lesson built fine when I temporarily moved it to the raster repo and built locally.  Are we ready to transfer them across from the template repo?  

2) Alternatively this could be replaced with a different file but there does need to some downloadable data for them to use.  

3) Additionally, do we want this lesson on Data Skills at this time.  It is a how-to but not a lesson in the form of our others.

**Comment by lwasser** [comment]
Hi @mjones01 . Please move this lesson to the data lesson development repository for the time being. Let's fix it first, then move it to NDS. Next steps.

1. Revert the merge where you submitted the file - missing include files will break Jekyll builds
2. Create a PR to add it to the NEON Data lesson Development repo. 
3. Create an issue to review the lesson and assign it to me in the data lesson dev repo.
4. resolve this issue once the above is complete. 

Thank you!
Leah

**Comment by mjones01** [comment]
@lwasser  Lesson Development repo also does not have the Download Data _include files.  Do you want me to add them at this time?  Or just add the single _include for this lesson.

**Comment by mjones01** [comment]
* Removed from Data Skills repo (https://github.com/NEONInc/NEON-Data-Skills/pull/57)
* Added to Lesson Development repo (https://github.com/NEONInc/NEON-DataSkills-Lesson-Development/pull/9)

close issue
